<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="4" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="231" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="231" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
      <class name="com.nuance.him.service.customer.CustomerServiceImplTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="setUp" is-config="true" duration-ms="166" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testAddCustomer()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="testAddCustomer" duration-ms="22" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddCustomer -->
        <test-method status="PASS" signature="testAddCustomerException()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="testAddCustomerException" duration-ms="3" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <exception class="com.nuance.him.service.serviceexception.CustomerServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.CustomerServiceException: 
at com.nuance.him.service.customer.CustomerServiceImpl.addCustomer(CustomerServiceImpl.java:33)
at com.nuance.him.service.customer.CustomerServiceImplTest.testAddCustomerException(CustomerServiceImplTest.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.CustomerServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddCustomerException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDisplayCustomer()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="testDisplayCustomer" duration-ms="1" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDisplayCustomer -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDisplayCustomerException()[pri:0, instance:com.nuance.him.service.customer.CustomerServiceImplTest@5cc7c2a6]" name="testDisplayCustomerException" duration-ms="0" started-at="2019-01-11T11:13:13 IST" finished-at="2019-01-11T11:13:13 IST">
          <exception class="com.nuance.him.service.serviceexception.CustomerServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.CustomerServiceException: 
at com.nuance.him.service.customer.CustomerServiceImpl.getAllCustomers(CustomerServiceImpl.java:41)
at com.nuance.him.service.customer.CustomerServiceImplTest.testDisplayCustomerException(CustomerServiceImplTest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:129)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:113)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.CustomerServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDisplayCustomerException -->
      </class> <!-- com.nuance.him.service.customer.CustomerServiceImplTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
